name: BUILD_and_PUSH_Docker_Image

on:

  push:
    branches: [ test ]
    
  pull_request:
    branches: [ master ]
    
  schedule:
    - cron:  '37 */2 * * *'

  workflow_dispatch:

jobs:

  BUILD_and_PUSH_Docker_Image:
    runs-on: ubuntu-latest
    steps:

      - name: Clone this repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
           DOCKER_HUB_SECRET: '${{ secrets.DOCKER_HUB_SECRET }}'
        with:
          username: skoralex
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Run check new version pritunl
        id: version
        shell: bash
        env:
           DOCKER_HUB_SECRET: '${{ secrets.DOCKER_HUB_SECRET }}'
           TGKEY: '${{ secrets.TGKEY }}'
           TLG_DLINK_CHAT_ID: '${{ secrets.TLG_DLINK_CHAT_ID }}'
        run: |
            docker buildx inspect --bootstrap    
            version=$(curl -sL https://api.github.com/repos/pritunl/pritunl/releases/latest | jq -r ".tag_name")
            version_hub=$(curl -L --fail "https://hub.docker.com/v2/repositories/skoralex/pritunl/tags/?page_size=1000" | jq '.results | .[] | .name' -r | sed 's/latest//' | sort --version-sort|tail -n 1)
            if [ "$version" != "$version_hub" ]
            then
            export $(cat .env | xargs)
            echo "::set-output name=version::$version"
            echo "::set-output name=go_version::$GO_VERSION"
            echo "::set-output name=version_new::true"
            message="Update pritunl! version=$version version_hub=$version_hub"
            curl -s https://api.telegram.org/bot"$TGKEY"/sendMessage  -d "chat_id=$-1001194479469" -d "text=Test!"
            else
            echo "version=$version version_hub=$version_hub Not update!"
            echo "::set-output name=version_new::false"
            fi

      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.version.outputs.version_new == 'true'
        with:
          context: .
          build-args: |
            GO_VERSION=${{ steps.version.outputs.go_version }}
            VERSION=${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: skoralex/pritunl:latest, skoralex/pritunl:${{ steps.version.outputs.version }}

  SEND_FAIL_DEPLOY:

    runs-on: ubuntu-latest

    if: ${{ failure() }}
    needs: [ BUILD_and_PUSH_Docker_Image ]

    steps:

     - name: send to tlg fail
       env:
         TGKEY: '${{ secrets.TGKEY }}'
         TLG_DLINK_CHAT_ID: '${{ secrets.TLG_DLINK_CHAT_ID }}'
       run: |
           curl -s https://api.telegram.org/bot"$TGKEY"/sendMessage -d  "chat_id=-1001194479469" -d "text=Test!"
          
